export const ADD_POLL_REQUEST = 'ADD_POLL_REQUEST';
export const ADD_POLL_SUCCESS = 'ADD_POLL_SUCCESS';
export const ADD_POLL_FAILURE = 'ADD_POLL_FAILURE';
export const ADD_POLL_INVALID = 'ADD_POLL_INVALID';
export const VOTE_REQUEST = 'VOTE_REQUEST';
export const VOTE_SUCCESS = 'VOTE_SUCCESS';
export const VOTE_FAILURE = 'VOTE_FAILURE';
export const VOTE_INVALID = 'VOTE_INVALID';
export const FETCH_POLLS_REQUEST = 'FETCH_POLLS_REQUEST';
export const FETCH_POLLS_SUCCESS = 'FETCH_POLLS_SUCCESS';
export const FETCH_POLLS_FAILURE = 'FETCH_POLLS_FAILURE';
export const FETCH_POLL_REQUEST = 'FETCH_POLL_REQUEST';
export const FETCH_POLL_SUCCESS = 'FETCH_POLL_SUCCESS';
export const FETCH_POLL_FAILURE = 'FETCH_POLL_FAILURE';
export const FETCH_TOKEN_REQUEST = 'FETCH_TOKEN_REQUEST';
export const FETCH_TOKEN_SUCCESS = 'FETCH_TOKEN_SUCCESS';
export const FETCH_TOKEN_FAILURE = 'FETCH_TOKEN_FAILURE';
export const FETCH_TOKEN_NON_FIELD_ERRORS = 'FETCH_TOKEN_NON_FIELD_ERRORS';
export const FETCH_TOKEN_FIELD_ERRORS = 'FETCH_TOKEN_FIELD_ERRORS';
export const VOTE_TYPE = {
    YES: 'y',
    NOT_SURE: '?',
    NO: 'n'
};